version: '3.8'

services:
  api:
    build: .
    volumes:
      - .:/app
    ports:
      - 3001:3000
    command: ['npm', 'run', 'dev']
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - ./db:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: testing
